### PR TITLE
Added some features

### PR DESCRIPTION
**Pull request by nachoe40**
Hi zonak, 
I added some features to your task, I hope you could add it to your project.
The new features are:
* Added intelligence to upload only changed files (checks by timestamp and file size)
* Added an option to force upload (ignore modification check)
* Added an option to sync server files and folders (delete extra files and folders from destination)
* Added an option to keep certain files or folders in destination (avoid deleting from destination)
* Improve paths management with path.join

The only known issue I found is that if it tries to delete a file and fails (for lack of permissions or is locked by some process) it enters an infinite loop. (but I will try to fix it soon).
Any comments or doubts please let me know

nacho

### CODE REVIEW

**Comment by charliedowler** [comment]
Hey,

The indentation makes it difficult to diff your changes.

If you revert the indentation then squash your commits, the diffs should be much clearer.

(Thats if it's @zonak is ok with the feature additions!)

Cheers

**Comment by nachoe40** [comment]
Hey, I fixed the indentation, tell me if it's ok

**Comment by nachoe40** [comment]
Sorry, I just noticed the line endings were Windows format.

**Comment by zonak** [comment]
Thank you for all the hard work - have been really busy but I want and will check this out more closely.

These are rather big changes but if we leave these new features optional behind a setting I think it would be great.

**Comment by nachoe40** [comment]
Thanks! I've already added a config entry for each new feature.
Any help you need just let me know.

**Comment by Rainbowlemon** [comment]
+1, would love to see timestamp/filesize checking soon - working on a fairly big repo and it's a pain having to upload everything every time!

**Comment by Mike-Veigel** [comment]
Any update on this?  These features would be very helpful!

**Comment by zonak** [comment]
@nachoe40 I want to thank you again for all the hard work but I am a user of this task myself and with these changes in place I would not use it. I just want something that will upload my files without the prospect of something getting deleted (there are a bunch of circumstances where that might happen).
If you publish a fork I'd be more than happy to mention it in the `readme`.
Sorry it took me this long but time was tight.

**Comment by nachoe40** [comment]
Oh, sorry to hear that. 
Thanks anyways for your time!
Just one question, when you say "there are a bunch of circumstances where that might happen" you mean even if it is configured to not syncing the server side??

**Comment by zonak** [comment]
Well proper configuration would prevent it - but people make mistakes in
configurations as well. Sorry for not explaining myself too good.

With only pushing files up on the server you have a way out without
starting to dig through backups.

I understand that there use cases where people would find value in deleting
stuff on the server as a part of deployment but not in our use cases.

**Comment by nachoe40** [comment]
Ok, I get it now.
Probably I will make a fork, so I'll let you know.
Regards!

**Pull request closed without merging**
